---
title: "Gov 50 Final Project"
author: "Sa'maia Evans"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the impact or correlation of certain factors of an academic environment on the performance of black students in primary and secondary education. This would likely be data collected from a natural observatory experiment. 

```{r}
library(tidyverse)

chicago <- 
  read.csv("chicago_public_schools.csv")

head(chicago) |> 
  select(School.ID,ZIP.Code,Safety.Icon,Environment.Score,Rate.of.Misconducts..per.100.students., Safety.Score, Parent.Environment.Score, College.Enrollment.Rate.., Community.Area.Name, Police.District)

```

## Proposal

Does a school environment and location influence student behaviors or performance in school? In this study, I plan to examine the extent to which the safety levels of a school environment impact student behavior, measured by the rates of misconduct amongst their student body. I hypothesize that there is a negative correlation between these two factors and that as a school's safety level decreases, their rates of misconduct among their student body increases. As the safety levels of schools decreases, students feel less safe in school and therefore are more likely to allow these feelings to manifest in their own behviors, and may feel as though the lack of safety provides more of a reason ot act defensively and in noncompliance with school rules. My data is compromised of 556 public schools in the Chicago, Illinois area, and was used to create the report cards of Chicago Public Schools in the 2011-2012 school year. My unit of analysis are the individual schools, each identified by a unique ID number, and the explanatory variable in this study is the safety score of the school, measured on a scale of 1 - 99. In this variable, 1 represents a score that is at least 2.5 standard deviations below the given benchmark, and score of 99 represents a score that is at least 2.5 standard deviations above the benchmark. These values were determined by the "5Essentials" survey that is has been administered in Chicago Public Schools since 1990 to measure schools' performances in different categories. My outcome variable is the rate of misconduct, representative of the number of misconducts per 100 students. If I observe that a school has higher rates of misconduct while aslo having lower safety ratings (closer to 1 than 99), then this would provide evidence in support of my hypothesis. If instead, I observe that a school has higher safety ratings (closer to 99 than 1), then this would provide evidence against my hypothesis. When I run my linear regression of the misconduct rates on the safety score variable, a negative correlation would indicate support for my hypothesis. 